### ISSUE TITLE
Add gnomad_qc to requirements file

### ISSUE THREAD

**Issue by ch-kr** [broadinstitute/gnomad-constraint#13]
Ruchit was running code in the RMC [repo](https://github.com/broadinstitute/regional_missense_constraint/tree/main) and found that he needed to import the gnomad_qc repo. The RMC repo does not import code from gnomad_qc, but it imports code from this repo, which relies on gnomad_qc:
```
Traceback (most recent call last):
  File "/tmp/624521a536a54578b9f93b99d1d4524f/calculate_mpc.py", line 17, in <module>
    from rmc.utils.mpc import (
  File "/tmp/624521a536a54578b9f93b99d1d4524f/pyscripts_8dkg66yu.zip/rmc/utils/__init__.py", line 1, in <module>
  File "/tmp/624521a536a54578b9f93b99d1d4524f/pyscripts_8dkg66yu.zip/rmc/utils/constraint.py", line 41, in <module>
  File "/tmp/624521a536a54578b9f93b99d1d4524f/pyscripts_8dkg66yu.zip/rmc/utils/generic.py", line 20, in <module>
  File "/opt/conda/default/lib/python3.10/site-packages/gnomad_constraint/utils/constraint.py", line 36, in <module>
    from gnomad_constraint.resources.resource_utils import (
  File "/opt/conda/default/lib/python3.10/site-packages/gnomad_constraint/resources/resource_utils.py", line 17, in <module>
    from gnomad_qc.v4.resources.release import release_coverage, release_sites
ModuleNotFoundError: No module named 'gnomad_qc'
```
It would be super helpful to add gnomad_qc to the requirements for this repo!

**Comment by klaricch** [comment]
gnomad_qc and gnomad_methods have already been included at the top of the requirements file above the part that is automatically generated 

https://github.com/broadinstitute/gnomad-constraint/blob/e8b42132bf2874e7af611af72aecf801afa7aaaa/requirements-dev.txt#L4
